name: Run Tests
description: Composite action to run tests with LS-DYNA keyword server

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.13"
    type: string

  github-token:
    description: GitHub token for authentication
    required: true

  pytest-markers:
    description: Pytest markers to use (e.g., 'run', 'keywords')
    required: false
    default: ""
    type: string

  docker-image:
    description: Docker image to use for LS-DYNA keyword server
    required: false
    default: "ghcr.io/ansys/pydyna-run:latest"
    type: string

  server-logs:
    description: Whether to extract server logs
    required: false
    default: "false"
    type: boolean

  license-server:
    description: License server for LS-DYNA
    required: false
    default: ""
    type: string

  codecov-token:
    description: Token for Codecov upload
    required: false
    default: ""
    type: string

  coverage-file:
    description: Coverage file path
    required: false
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
          persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: ${{ inputs.python-version }}


    - name: Create virtual environment
      shell: bash
      run: |
        python -m venv .venv

    - name: Login to GitHub container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}


    - name: Pull and start LS-DYNA keyword server
      if: ${{ inputs.docker-image != '' && inputs.pytest-markers != '' }}
      env:
        DOCKER_IMAGE: ${{ inputs.docker-image }}
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          source .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        uv pip install docker
        docker pull "$DOCKER_IMAGE"
        docker run -d --name kw_server -p 50051:50051 "$DOCKER_IMAGE" && echo "Keyword server active on port 50051."
      shell: bash

    - name: Install test dependencies
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          source .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        uv pip install -e .[tests]
      shell: bash

    - name: Run pytest
      env:
        PYTEST_MARKERS: ${{ inputs.pytest-markers }}
        COVERAGE_FILE: ${{ inputs.coverage-file }}
        PYDYNA_RUN_CONTAINER: ${{ inputs.docker-image }}
        ANSYSLI_SERVERS: 2325@${{ inputs.license-server }}
        ANSYSLMD_LICENSE_FILE: 1055@${{ inputs.license-server }}
        LSTC_LICENSE: ansys
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          source .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        COVERAGE_ARGS=""
        if [ -n "$COVERAGE_FILE" ]; then
          COVERAGE_ARGS="--cov=ansys.dyna.core --cov-report html:.cov/html --cov-report xml:.cov/xml --cov-report term"
        fi

        if [ "$PYTEST_MARKERS" = "" ]; then
          pytest -ra $COVERAGE_ARGS -vv
        else
          pytest -m "$PYTEST_MARKERS" -ra $COVERAGE_ARGS -vv
        fi
      shell: bash

    - name: Extract the server logs
      if: ${{ inputs.server-logs == 'true' }}
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          source .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        docker logs kw_server > server_output.txt
      shell: bash

    - name: Upload the server logs
      if: ${{ inputs.server-logs == 'true' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: server_output_tests.txt
        path: server_output.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
      with:
        flags: ${{ inputs.coverage-file }}

    - name: Stop container
      if: ${{ inputs.docker-image != '' && inputs.pytest-markers != 'keywords' }}
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          source .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        docker stop kw_server
        docker rm kw_server
      shell: bash