version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    groups:
      doc:
        patterns:
          - "*sphinx*"
          - "jupyter*"
          - "imageio*"
          - "ipython"
          - "numpydoc"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "ci"
    groups:
       actions:
          patterns:
            - "*"

