# -- Labels based on PR title ------------------------------------------------

'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']

# -- Documentation labels ----------------------------------------------------

'documentation':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/**/*.rst', 'README.rst']

'maintenance':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['.github/**/*', 'pyproject.toml', '.flake8']
'dependencies':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['pyproject.toml']
'testing':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['_unittest/conftest.py', 'tests/*']
'ci':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

# HACK: the following labels are declared with the only purpose of avoiding the
# GitHub labeler bot to remove those. This is a known issue reported in the
# official action/labeler repo https://github.com/actions/labeler/issues/763

'ci:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'docs:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'tests:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

