- name: 'bug'
  description: Defects or glitches reported by users or developers
  color: d42a34

- name: 'fix'
  description:  Pull requests related to resolving problems or errors
  color: d42a34

- name: 'dependencies'
  description: Related with project dependencies
  color: fabed4

- name: 'documentation'
  description: Improvements or additions to documentation
  color: 0677ba

- name: 'enhancement'
  description: General improvements to existing features
  color: ffd827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: 'maintenance'
  description: Generic maintenance related
  color: f78c37

- name: 'release'
  description: Anything related to an incoming release
  color: fe66d1

- name: 'testing'
  description: Anything related to testing
  color: 5802B8

- name: 'ci'
  description: Pipelines maintenance related
  color: a9a9a9

- name: 'Keywords'
  description: Anything related to keyword subpackage
  color: 5802B8

- name: 'Run'
  description: Anything related to run subpackage
  color: 25c1ea

- name: 'Solver'
  description: Anything related to solver subpackage
  color: 7e505b

- name: 'Pre'
  description: Anything related to pre subpackage
  color: 81854c