ci:
  autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'
  autoupdate_commit_msg: 'chore: pre-commit automatic update'
  autoupdate_schedule: weekly

exclude: |
    (?x)^(
        codegen/kwd.json|
        codegen/additional-cards.json|
        benchmarks/.*|
        doc/source/.*|
        tests/.*|
        src/ansys/dyna/core/keywords/keyword_classes/auto/|
        src/ansys/dyna/core/keywords/keyword_classes/type_mapping.py|
        src/ansys/dyna/core/keywords/keyword_classes/auto_keywords.py|
        src/ansys/dyna/core/keywords/keyword_classes/manual/.*_version_.*\.py|
        .*\.k$
    )
repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.5 #0.15.4
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2 # v2.4.1
  hooks:
  - id: codespell
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "-w"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0 # v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.0 # v0.37.0
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2 # v0.5.2
  hooks:
    - id: add-license-headers
      files: '(src|tests|doc)/.*\.(py)'
      args:
      - --start_year=2023

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: b546b77c44c466a54a42af5499dcc0dcc1a3193f # v0.22.0
  hooks:
    - id: zizmor
      args: ["--pedantic"]