coverage:
  range: 75..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 90%
    patch: off


codecov:
  notify:
    wait_for_ci: yes

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: run
      paths: 
      - src/ansys/dyna/core/run  
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: keywords
      paths: 
      - src/ansys/dyna/core/keywords  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
      - type: project
        target: 20%
      - type: patch
        target: 100%