# Copyright (C) 2021 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Auto-generated imports for contacts domain

from .contact_1d import Contact1D
from .contact_2d_automatic_node_to_surface import Contact2DAutomaticNodeToSurface
from .contact_2d_automatic_node_to_surface_thermal import Contact2DAutomaticNodeToSurfaceThermal
from .contact_2d_automatic_one_way_surface_to_surface import Contact2DAutomaticOneWaySurfaceToSurface
from .contact_2d_automatic_one_way_surface_to_surface_thermal import Contact2DAutomaticOneWaySurfaceToSurfaceThermal
from .contact_2d_automatic_single_surface import Contact2DAutomaticSingleSurface
from .contact_2d_automatic_single_surface_mortar import Contact2DAutomaticSingleSurfaceMortar
from .contact_2d_automatic_single_surface_mortar_thermal import Contact2DAutomaticSingleSurfaceMortarThermal
from .contact_2d_automatic_single_surface_thermal import Contact2DAutomaticSingleSurfaceThermal
from .contact_2d_automatic_surface_in_continuum import Contact2DAutomaticSurfaceInContinuum
from .contact_2d_automatic_surface_in_continuum_thermal import Contact2DAutomaticSurfaceInContinuumThermal
from .contact_2d_automatic_surface_to_surface import Contact2DAutomaticSurfaceToSurface
from .contact_2d_automatic_surface_to_surface_mortar import Contact2DAutomaticSurfaceToSurfaceMortar
from .contact_2d_automatic_surface_to_surface_mortar_thermal import Contact2DAutomaticSurfaceToSurfaceMortarThermal
from .contact_2d_automatic_surface_to_surface_thermal import Contact2DAutomaticSurfaceToSurfaceThermal
from .contact_2d_automatic_tied import Contact2DAutomaticTied
from .contact_2d_automatic_tied_one_way import Contact2DAutomaticTiedOneWay
from .contact_2d_automatic_tied_one_way_thermal import Contact2DAutomaticTiedOneWayThermal
from .contact_2d_automatic_tied_thermal import Contact2DAutomaticTiedThermal
from .contact_2d_force_transducer import Contact2DForceTransducer
from .contact_2d_node_to_solid import Contact2DNodeToSolid
from .contact_2d_node_to_solid_tied import Contact2DNodeToSolidTied
from .contact_2d_penalty import Contact2DPenalty
from .contact_2d_penalty_friction import Contact2DPenaltyFriction
from .contact_2d_sliding_only import Contact2DSlidingOnly
from .contact_2d_sliding_voids import Contact2DSlidingVoids
from .contact_2d_tied_sliding import Contact2DTiedSliding
from .contact_add_wear import ContactAddWear
from .contact_airbag_single_surface import ContactAirbagSingleSurface
from .contact_automatic_beams_to_surface import ContactAutomaticBeamsToSurface
from .contact_automatic_general import ContactAutomaticGeneral
from .contact_automatic_general_edgeonly import ContactAutomaticGeneralEdgeonly
from .contact_automatic_general_interior import ContactAutomaticGeneralInterior
from .contact_automatic_general_tiebreak import ContactAutomaticGeneralTiebreak
from .contact_automatic_general_tiebreak_beam_offset import ContactAutomaticGeneralTiebreakBeamOffset
from .contact_automatic_nodes_to_surface import ContactAutomaticNodesToSurface
from .contact_automatic_nodes_to_surface_smooth import ContactAutomaticNodesToSurfaceSmooth
from .contact_automatic_one_way_surface_to_surface import ContactAutomaticOneWaySurfaceToSurface
from .contact_automatic_one_way_surface_to_surface_ortho_friction import ContactAutomaticOneWaySurfaceToSurfaceOrthoFriction
from .contact_automatic_one_way_surface_to_surface_smooth import ContactAutomaticOneWaySurfaceToSurfaceSmooth
from .contact_automatic_one_way_surface_to_surface_tiebreak import ContactAutomaticOneWaySurfaceToSurfaceTiebreak
from .contact_automatic_one_way_surface_to_surface_tiebreak_damping import ContactAutomaticOneWaySurfaceToSurfaceTiebreakDamping
from .contact_automatic_one_way_surface_to_surface_tiebreak_user import ContactAutomaticOneWaySurfaceToSurfaceTiebreakUser
from .contact_automatic_single import ContactAutomaticSingle
from .contact_automatic_single_surface import ContactAutomaticSingleSurface
from .contact_automatic_single_surface_mortar import ContactAutomaticSingleSurfaceMortar
from .contact_automatic_single_surface_smooth import ContactAutomaticSingleSurfaceSmooth
from .contact_automatic_single_surface_tiebreak import ContactAutomaticSingleSurfaceTiebreak
from .contact_automatic_single_surface_tiebreak_beam_offset import ContactAutomaticSingleSurfaceTiebreakBeamOffset
from .contact_automatic_single_surface_tied import ContactAutomaticSingleSurfaceTied
from .contact_automatic_surface_to_surface import ContactAutomaticSurfaceToSurface
from .contact_automatic_surface_to_surface_composite import ContactAutomaticSurfaceToSurfaceComposite
from .contact_automatic_surface_to_surface_mortar import ContactAutomaticSurfaceToSurfaceMortar
from .contact_automatic_surface_to_surface_mortar_tied import ContactAutomaticSurfaceToSurfaceMortarTied
from .contact_automatic_surface_to_surface_mortar_tied_weld import ContactAutomaticSurfaceToSurfaceMortarTiedWeld
from .contact_automatic_surface_to_surface_ortho_friction import ContactAutomaticSurfaceToSurfaceOrthoFriction
from .contact_automatic_surface_to_surface_smooth import ContactAutomaticSurfaceToSurfaceSmooth
from .contact_automatic_surface_to_surface_tiebreak import ContactAutomaticSurfaceToSurfaceTiebreak
from .contact_automatic_surface_to_surface_tiebreak_damping import ContactAutomaticSurfaceToSurfaceTiebreakDamping
from .contact_automatic_surface_to_surface_tiebreak_mortar import ContactAutomaticSurfaceToSurfaceTiebreakMortar
from .contact_automatic_surface_to_surface_tiebreak_user import ContactAutomaticSurfaceToSurfaceTiebreakUser
from .contact_automatic_surface_to_surface_tiebreak_user_mortar import ContactAutomaticSurfaceToSurfaceTiebreakUserMortar
from .contact_automatic_surface_to_surface_tied_weld import ContactAutomaticSurfaceToSurfaceTiedWeld
from .contact_auto_move import ContactAutoMove
from .contact_constraint_nodes_to_surface import ContactConstraintNodesToSurface
from .contact_constraint_surface_to_surface import ContactConstraintSurfaceToSurface
from .contact_coupling import ContactCoupling
from .contact_drawbead import ContactDrawbead
from .contact_drawbead_bending import ContactDrawbeadBending
from .contact_drawbead_initialize import ContactDrawbeadInitialize
from .contact_entity import ContactEntity
from .contact_eroding_nodes_to_surface import ContactErodingNodesToSurface
from .contact_eroding_single_surface import ContactErodingSingleSurface
from .contact_eroding_surface_to_surface import ContactErodingSurfaceToSurface
from .contact_exclude_interaction import ContactExcludeInteraction
from .contact_force_transducer import ContactForceTransducer
from .contact_force_transducer_constraint import ContactForceTransducerConstraint
from .contact_force_transducer_penalty import ContactForceTransducerPenalty
from .contact_forming_nodes_to_surface import ContactFormingNodesToSurface
from .contact_forming_nodes_to_surface_smooth import ContactFormingNodesToSurfaceSmooth
from .contact_forming_one_way_surface_to_surface import ContactFormingOneWaySurfaceToSurface
from .contact_forming_one_way_surface_to_surface_ortho_friction import ContactFormingOneWaySurfaceToSurfaceOrthoFriction
from .contact_forming_one_way_surface_to_surface_smooth import ContactFormingOneWaySurfaceToSurfaceSmooth
from .contact_forming_surface_to_surface import ContactFormingSurfaceToSurface
from .contact_forming_surface_to_surface_mortar import ContactFormingSurfaceToSurfaceMortar
from .contact_forming_surface_to_surface_smooth import ContactFormingSurfaceToSurfaceSmooth
from .contact_gebod_head import ContactGebodHead
from .contact_gebod_left_foot import ContactGebodLeftFoot
from .contact_gebod_left_hand import ContactGebodLeftHand
from .contact_gebod_left_lower_arm import ContactGebodLeftLowerArm
from .contact_gebod_left_lower_leg import ContactGebodLeftLowerLeg
from .contact_gebod_left_shoulder import ContactGebodLeftShoulder
from .contact_gebod_left_upper_arm import ContactGebodLeftUpperArm
from .contact_gebod_left_upper_leg import ContactGebodLeftUpperLeg
from .contact_gebod_lower_torso import ContactGebodLowerTorso
from .contact_gebod_middle_torso import ContactGebodMiddleTorso
from .contact_gebod_neck import ContactGebodNeck
from .contact_gebod_right_foot import ContactGebodRightFoot
from .contact_gebod_right_hand import ContactGebodRightHand
from .contact_gebod_right_lower_arm import ContactGebodRightLowerArm
from .contact_gebod_right_lower_leg import ContactGebodRightLowerLeg
from .contact_gebod_right_shoulder import ContactGebodRightShoulder
from .contact_gebod_right_upper_arm import ContactGebodRightUpperArm
from .contact_gebod_right_upper_leg import ContactGebodRightUpperLeg
from .contact_gebod_upper_torso import ContactGebodUpperTorso
from .contact_guided_cable import ContactGuidedCable
from .contact_guided_cable_set import ContactGuidedCableSet
from .contact_interior import ContactInterior
from .contact_nodes_to_surface import ContactNodesToSurface
from .contact_nodes_to_surface_interference import ContactNodesToSurfaceInterference
from .contact_nodes_to_surface_smooth import ContactNodesToSurfaceSmooth
from .contact_nurbs_tied_edge_to_edge import ContactNurbsTiedEdgeToEdge
from .contact_nurbs_tied_edge_to_surface import ContactNurbsTiedEdgeToSurface
from .contact_nurbs_tied_nodes_to_surface import ContactNurbsTiedNodesToSurface
from .contact_one_way_surface_to_surface import ContactOneWaySurfaceToSurface
from .contact_one_way_surface_to_surface_interference import ContactOneWaySurfaceToSurfaceInterference
from .contact_one_way_surface_to_surface_smooth import ContactOneWaySurfaceToSurfaceSmooth
from .contact_rigid_body_one_way_to_rigid_body import ContactRigidBodyOneWayToRigidBody
from .contact_rigid_body_two_way_to_rigid_body import ContactRigidBodyTwoWayToRigidBody
from .contact_rigid_nodes_to_rigid_body import ContactRigidNodesToRigidBody
from .contact_rigid_surface import ContactRigidSurface
from .contact_single_edge import ContactSingleEdge
from .contact_single_surface import ContactSingleSurface
from .contact_sliding_only import ContactSlidingOnly
from .contact_sliding_only_penalty import ContactSlidingOnlyPenalty
from .contact_spg import ContactSpg
from .contact_spotweld import ContactSpotweld
from .contact_spotweld_beam_offset import ContactSpotweldBeamOffset
from .contact_spotweld_with_torsion import ContactSpotweldWithTorsion
from .contact_surface_to_surface import ContactSurfaceToSurface
from .contact_surface_to_surface_contraction_joint import ContactSurfaceToSurfaceContractionJoint
from .contact_surface_to_surface_interference import ContactSurfaceToSurfaceInterference
from .contact_surface_to_surface_smooth import ContactSurfaceToSurfaceSmooth
from .contact_surface_to_surface_thermal_friction import ContactSurfaceToSurfaceThermalFriction
from .contact_tiebreak_nodes_only import ContactTiebreakNodesOnly
from .contact_tiebreak_nodes_to_surface import ContactTiebreakNodesToSurface
from .contact_tiebreak_surface_to_surface import ContactTiebreakSurfaceToSurface
from .contact_tiebreak_surface_to_surface_only import ContactTiebreakSurfaceToSurfaceOnly
from .contact_tied_nodes_to_surface import ContactTiedNodesToSurface
from .contact_tied_nodes_to_surface_constrained_offset import ContactTiedNodesToSurfaceConstrainedOffset
from .contact_tied_nodes_to_surface_offset import ContactTiedNodesToSurfaceOffset
from .contact_tied_shell_edge_to import ContactTiedShellEdgeTo
from .contact_tied_shell_edge_to_solid import ContactTiedShellEdgeToSolid
from .contact_tied_shell_edge_to_solid_beam_offset import ContactTiedShellEdgeToSolidBeamOffset
from .contact_tied_shell_edge_to_solid_constrained_offset import ContactTiedShellEdgeToSolidConstrainedOffset
from .contact_tied_shell_edge_to_solid_offset import ContactTiedShellEdgeToSolidOffset
from .contact_tied_shell_edge_to_surface import ContactTiedShellEdgeToSurface
from .contact_tied_shell_edge_to_surface_beam_offset import ContactTiedShellEdgeToSurfaceBeamOffset
from .contact_tied_shell_edge_to_surface_constrained_offset import ContactTiedShellEdgeToSurfaceConstrainedOffset
from .contact_tied_shell_edge_to_surface_offset import ContactTiedShellEdgeToSurfaceOffset
from .contact_tied_surface_to_surface import ContactTiedSurfaceToSurface
from .contact_tied_surface_to_surface_constrained_offset import ContactTiedSurfaceToSurfaceConstrainedOffset
from .contact_tied_surface_to_surface_failure import ContactTiedSurfaceToSurfaceFailure
from .contact_tied_surface_to_surface_offset import ContactTiedSurfaceToSurfaceOffset
