name: Test codegen
description: Run the codegen tests

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.13"
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install library
      shell: bash
      run: pip install -e .[codegen]

    - name: Generate codegen
      shell: bash
      run: |
        python codegen/generate.py -c
        python codegen/generate.py

    - name: Run codegen testing
      shell: bash
      run: |
        if git -C src/ansys/dyna/core/keywords/keyword_classes/auto diff --relative --exit-code; then
          echo "CHANGES=false" >> "$GITHUB_ENV"
        else
          echo "CHANGES=true" >> "$GITHUB_ENV"
        fi

    - name: Exit on changes
      if: ${{ env.CHANGES == 'true' }}
      shell: bash
      run: exit 1
