name: Test codegen
description: Run the codegen tests

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.13"
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
          persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install library
      shell: bash
      run: pip install -e .[codegen]

    - name: Run codegen validation
      shell: bash
      run: bash codegen/validate.sh --skip-precommit --skip-deadcode --skip-tests
