name: Test codegen
description: Run the codegen tests

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.13"
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
          persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: "Create a virtual environment"
      shell: bash
      run: |
        python -m venv .venv

    - name: Install library
      shell: bash
      run: |
        source .venv/bin/activate
        uv pip install -e .[codegen]

    - name: Run codegen validation
      shell: bash
      run: |
        source .venv/bin/activate
        bash codegen/validate.sh --skip-precommit --skip-deadcode