$-------------------------------------BOF---------------------------------------
*KEYWORD
$
$-- storage temp:  23 °C
$-- tank volume :  60 liter
$
*DEFINE_CURVE_TITLE
$# title
XYZ
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp
  46500001,        0,      1.0,   1.0E-3, <PAB_TTF-1.1>
$          time [ms]           mf [kg/s]
      0.00000000E+00      0.00000000E+00
       9.99990000E+03      0.00000000E+00
*END
$-------------------------------------EOF---------------------------------------
