# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os
import pathlib
import typing

from jinja2 import Environment
from keyword_generation.utils import get_license_header
from keyword_generation.utils.domain_mapper import get_all_domains, get_keyword_domain


def generate_entrypoints(env: Environment, lib_path: str, keywords_list: typing.List[typing.Dict]) -> None:
    """use templates to write keywords/type_mapping.py, keywords/__init__.py and domain __init__.py files"""
    license_header = get_license_header()
    keywords_lists = {"license": license_header, "keywords": keywords_list}
    with open(os.path.join(lib_path, "auto_keywords.py"), "w", encoding="utf-8") as f:
        f.write(env.get_template("importer.j2").render(**keywords_lists))

    with open(os.path.join(lib_path, "type_mapping.py"), "w", encoding="utf-8") as f:
        f.write(env.get_template("type-mapping.j2").render(**keywords_lists))

    # Create domain-organized __init__.py files
    auto_path = pathlib.Path(lib_path) / "auto"

    # Group keywords by domain
    keywords_by_domain = {}
    for keyword in keywords_list:
        # Only include keywords that are auto-generated
        if keyword.get("is_autogenerated", True):
            domain = get_keyword_domain(keyword["name"])
            if domain not in keywords_by_domain:
                keywords_by_domain[domain] = []
            keywords_by_domain[domain].append(keyword)

    # Create __init__.py for each domain
    for domain in get_all_domains():
        domain_path = auto_path / domain
        domain_path.mkdir(parents=True, exist_ok=True)

        domain_keywords = keywords_by_domain.get(domain, [])
        init_content = license_header
        if domain_keywords:
            init_content += "\n# Auto-generated imports for " + domain + " domain\n\n"
            for keyword in domain_keywords:
                filename = keyword["filename"]
                classname = keyword["classname"]
                init_content += f"from .{filename} import {classname}\n"

        init_file = domain_path / "__init__.py"
        with open(init_file, "w", encoding="utf-8") as f:
            f.write(init_content)

    # Create main auto/__init__.py that imports from all domains
    main_init_content = license_header + "\n# Auto-generated imports from all domains\n\n"
    for domain in get_all_domains():
        main_init_content += f"from .{domain} import *\n"

    with open(auto_path / "__init__.py", "w", encoding="utf-8") as f:
        f.write(main_init_content)
