# Copyright (C) 2023 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import typing

from jinja2 import Environment
from keyword_generation.generators.template_context import EntrypointTemplateContext
from keyword_generation.utils import get_license_header
from keyword_generation.utils.domain_mapper import get_keyword_domain


def generate_entrypoints(env: Environment, output_manager, keywords_list: typing.List[typing.Dict]) -> None:
    """
    Generate entrypoint files using templates: auto_keywords.py and type_mapping.py

    Args:
        env: Jinja2 environment with loaded templates
        output_manager: Handles writing output files
        keywords_list: List of keyword metadata dicts
    """
    license_header = get_license_header()
    context = EntrypointTemplateContext(license=license_header, keywords=keywords_list)
    
    # Write auto_keywords.py and type_mapping.py using structured context
    output_manager.write_auto_keywords_file(env.get_template("importer.j2").render(**context.to_dict()))
    output_manager.write_type_mapping_file(env.get_template("type-mapping.j2").render(**context.to_dict()))

    # Group keywords by domain
    keywords_by_domain = {}
    for keyword in keywords_list:
        # Only include keywords that are auto-generated
        if keyword.get("is_autogenerated", True):
            domain = get_keyword_domain(keyword["name"])
            if domain not in keywords_by_domain:
                keywords_by_domain[domain] = []
            keywords_by_domain[domain].append(keyword)

    # Create __init__.py only for domains that have keywords
    domains_with_keywords = []
    for domain, keywords in keywords_by_domain.items():
        domains_with_keywords.append(domain)
        init_content = license_header
        if keywords:
            init_content += "\n# Auto-generated imports for " + domain + " domain\n\n"
            for keyword in keywords:
                filename = keyword["filename"]
                classname = keyword["classname"]
                init_content += f"from .{filename} import {classname}\n"
        output_manager.write_domain_init_file(domain, init_content)

    # Create main auto/__init__.py that imports only from domains with keywords
    main_init_content = license_header + "\n# Auto-generated imports from all domains\n\n"
    for domain in sorted(domains_with_keywords):
        main_init_content += f"from .{domain} import *\n"
    output_manager.write_main_init_file(main_init_content)
