*KEYWORD  
*PART
$#                                                                         title

$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         1         1         1         0         0         0         0         0
*SECTION_SOLID
$#   secid    elform       aet    unused    unused    unused    cohoff   gaskeit
         1         1         0                                     0.0       0.0
*MAT_PIECEWISE_LINEAR_PLASTICITY
$#     mid        ro         e        pr      sigy      etan      fail      tdel
         17.80000E-9  210000.0       0.3     100.0       1.01.00000E21       0.0
$#       c         p      lcss      lcsr        vp  
                             0         0       0.0
$#    eps1      eps2      eps3      eps4      eps5      eps6      eps7      eps8
                                                                                
$#     es1       es2       es3       es4       es5       es6       es7       es8                                                                              
*ELEMENT_SOLID
$#   eid     pid      n1      n2      n3      n4      n5      n6      n7      n8
       1       1       1       2       8       7      13      14      20      19
       2       1       2       3       9       8      14      15      21      20
       3       1       3       4      10       9      15      16      22      21
       4       1       4       5      11      10      16      17      23      22
       5       1       5       6      12      11      17      18      24      23
*NODE
$#   nid               x               y               z      tc      rc  
       1             0.0             0.0             0.0       0       0
       2             4.0             0.0             0.0       0       0
       3             8.0             0.0             0.0       0       0
       4            12.0             0.0             0.0       0       0
       5            16.0             0.0             0.0       0       0
       6            20.0             0.0             0.0       0       0
       7             0.0             4.0             0.0       0       0
       8             4.0             4.0             0.0       0       0
       9             8.0             4.0             0.0       0       0
      10            12.0             4.0             0.0       0       0
      11            16.0             4.0             0.0       0       0
      12            20.0             4.0             0.0       0       0
      13             0.0             0.0             4.0       0       0
      14             4.0             0.0             4.0       0       0
      15             8.0             0.0             4.0       0       0
      16            12.0             0.0             4.0       0       0
      17            16.0             0.0             4.0       0       0
      18            20.0             0.0             4.0       0       0
      19             0.0             4.0             4.0       0       0
      20             4.0             4.0             4.0       0       0
      21             8.0             4.0             4.0       0       0
      22            12.0             4.0             4.0       0       0
      23            16.0             4.0             4.0       0       0
      24            20.0             4.0             4.0       0       0
*END
