name: Documentation Build
description: Composite action to build and upload documentation (HTML and PDF)

inputs:

  build-autokeywords-api:
    description: Enable building the autokeywords API
    required: false
    default: "False"
  pdf-pool-size:
    required: false
  pdf-string-vacancies:
    required: false
  pdf-max-strings:
    required: false
  PyDynaRunContainer:
    description: Run container name
    required: true
  python-version:
    description: Python version to use
    required: true
    default: "3.13"
    type: string
  github-token:
    description: GitHub token for authentication
    required: true

  license-server:
    description: License server address
    required: true

  bot-token:
    description: Bot token for authentication
    required: true
  
  github-actor:
    description: GitHub actor for authentication
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout project
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: true

    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: set up virtual environment
      run: |
        python -m venv .venv
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install xvfb pandoc texlive-latex-extra latexmk
      shell: bash

    - name: Cache Sphinx build artifacts
      if: ${{ inputs.build-autokeywords-api != 'True' }}
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb #v5.0.1
      with:
        path: |
          doc/_build
          doc/source/examples/
        key: sphinx-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('doc/source/**/*.rst', 'doc/source/conf.py', 'pyproject.toml', 'examples/**/*') }}
        restore-keys: |
          sphinx-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Install python dependencies
      run: |
        source .venv/bin/activate
        uv pip install .[doc]
        uv pip install docker
      shell: bash

    - name: Set Licensing
      run: |
        echo "ANSYS_DPF_ACCEPT_LA=Y" >> $GITHUB_ENV
      shell: bash

    - name: Install DPF
      uses: ansys/pydpf-actions/install-dpf-server@v2.3 # zizmor: ignore[unpinned-uses]
      with:
        dpf-standalone-TOKEN: ${{ inputs.bot-token }}
        ANSYS_VERSION: "242"

    - name: Login to GitHub container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Set Licensing
      run: |
        echo "ANSYS_DPF_ACCEPT_LA=Y" >> $GITHUB_ENV
      shell: bash

    - name: Pull PyDyna-run image
      run: |
        source .venv/bin/activate
        docker pull ghcr.io/ansys/pydyna-run:latest
      shell: bash

    - name: Build the html documentation
      env:
        ANSYSLI_SERVERS: 2325@${{ inputs.license-server }}
        ANSYSLMD_LICENSE_FILE: 1055@${{ inputs.license-server }}
        PYDYNA_RUN_CONTAINER: ${{ inputs.PyDynaRunContainer }}
        BUILD_AUTOKEYWORDS_API: ${{ inputs.build-autokeywords-api }}
        LSTC_LICENSE: ansys
      run: |
        source .venv/bin/activate
        timeout 7200 xvfb-run uv run --no-sync -- make -C doc html SPHINXOPTS="-j auto"
      shell: bash

    - name: Upload html documentation
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: documentation-html
        path: doc/_build/html
        retention-days: 7

    - name: "Build the pdf documentation"
      shell: bash
      run: |
        source .venv/bin/activate
        xvfb-run uv run --no-sync -- make -C doc pdf
      env:
        ANSYSLI_SERVERS: 2325@${{ inputs.license-server }}
        ANSYSLMD_LICENSE_FILE: 1055@${{ inputs.license-server }}
        LSTC_LICENSE: ansys
        PYDYNA_RUN_CONTAINER: ${{ inputs.PyDynaRunContainer }}
        PYDYNA_RUN_STREAM: "0"
        extra_mem_bot: 20000000
        extra_mem_top: 30000000
        pool_size: ${{ inputs.pdf-pool-size }}
        string_vacancies: ${{ inputs.pdf-string-vacancies }}
        max_strings: ${{ inputs.pdf-max-strings }}

    - name: Upload pdf documentation
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: documentation-pdf
        path: doc/_build/latex/*.pdf
        retention-days: 7

