*KEYWORD
*PART
$#                                                                         title
part-one
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
       1         1         1         0         0         0         0         0
*PART
$#                                                                         title
part-zero
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
       0         1         1         0         0         0         0         0
*ELEMENT_SHELL
$#   eid     pid      n1      n2      n3      n4      n5      n6      n7      n8
       1       1       1       2       3       4       0       0       0       0
*NODE
$#   nid               x               y               z      tc      rc
       1             0.0             0.0             0.0       0       0
       2             1.0             0.0             0.0       0       0
       3             1.0             1.0             0.0       0       0
       4             0.0             1.0             0.0       0       0
*END
