# Copyright (C) 2021 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Auto-generated imports for airbag domain

from .airbag_adiabatic_gas_model import AirbagAdiabaticGasModel
from .airbag_adiabatic_gas_model_id import AirbagAdiabaticGasModelId
from .airbag_ale import AirbagAle
from .airbag_fluid_and_gas import AirbagFluidAndGas
from .airbag_fluid_and_gas_id import AirbagFluidAndGasId
from .airbag_hybrid import AirbagHybrid
from .airbag_hybrid_chemkin import AirbagHybridChemkin
from .airbag_hybrid_chemkin_id import AirbagHybridChemkinId
from .airbag_hybrid_id import AirbagHybridId
from .airbag_hybrid_jetting import AirbagHybridJetting
from .airbag_hybrid_jetting_cm import AirbagHybridJettingCm
from .airbag_hybrid_jetting_cm_id import AirbagHybridJettingCmId
from .airbag_hybrid_jetting_id import AirbagHybridJettingId
from .airbag_interaction import AirbagInteraction
from .airbag_linear_fluid import AirbagLinearFluid
from .airbag_linear_fluid_id import AirbagLinearFluidId
from .airbag_load_curve import AirbagLoadCurve
from .airbag_load_curve_id import AirbagLoadCurveId
from .airbag_particle import AirbagParticle
from .airbag_particle_decomposition import AirbagParticleDecomposition
from .airbag_particle_decomposition_id import AirbagParticleDecompositionId
from .airbag_particle_decomposition_inflation import AirbagParticleDecompositionInflation
from .airbag_particle_decomposition_inflation_id import AirbagParticleDecompositionInflationId
from .airbag_particle_decomposition_inflation_segment import AirbagParticleDecompositionInflationSegment
from .airbag_particle_decomposition_inflation_segment_id import AirbagParticleDecompositionInflationSegmentId
from .airbag_particle_decomposition_inflation_segment_time import AirbagParticleDecompositionInflationSegmentTime
from .airbag_particle_decomposition_inflation_segment_time_id import AirbagParticleDecompositionInflationSegmentTimeId
from .airbag_particle_decomposition_inflation_time import AirbagParticleDecompositionInflationTime
from .airbag_particle_decomposition_inflation_time_id import AirbagParticleDecompositionInflationTimeId
from .airbag_particle_decomposition_jet import AirbagParticleDecompositionJet
from .airbag_particle_decomposition_jet_id import AirbagParticleDecompositionJetId
from .airbag_particle_decomposition_jet_segment import AirbagParticleDecompositionJetSegment
from .airbag_particle_decomposition_jet_segment_id import AirbagParticleDecompositionJetSegmentId
from .airbag_particle_decomposition_jet_segment_time import AirbagParticleDecompositionJetSegmentTime
from .airbag_particle_decomposition_jet_segment_time_id import AirbagParticleDecompositionJetSegmentTimeId
from .airbag_particle_decomposition_jet_time import AirbagParticleDecompositionJetTime
from .airbag_particle_decomposition_jet_time_id import AirbagParticleDecompositionJetTimeId
from .airbag_particle_decomposition_molefraction import AirbagParticleDecompositionMolefraction
from .airbag_particle_decomposition_molefraction_id import AirbagParticleDecompositionMolefractionId
from .airbag_particle_decomposition_molefraction_segment import AirbagParticleDecompositionMolefractionSegment
from .airbag_particle_decomposition_molefraction_segment_id import AirbagParticleDecompositionMolefractionSegmentId
from .airbag_particle_decomposition_molefraction_segment_time import AirbagParticleDecompositionMolefractionSegmentTime
from .airbag_particle_decomposition_molefraction_segment_time_id import AirbagParticleDecompositionMolefractionSegmentTimeId
from .airbag_particle_decomposition_molefraction_time import AirbagParticleDecompositionMolefractionTime
from .airbag_particle_decomposition_molefraction_time_id import AirbagParticleDecompositionMolefractionTimeId
from .airbag_particle_decomposition_segment import AirbagParticleDecompositionSegment
from .airbag_particle_decomposition_segment_id import AirbagParticleDecompositionSegmentId
from .airbag_particle_decomposition_segment_time import AirbagParticleDecompositionSegmentTime
from .airbag_particle_decomposition_segment_time_id import AirbagParticleDecompositionSegmentTimeId
from .airbag_particle_decomposition_time import AirbagParticleDecompositionTime
from .airbag_particle_decomposition_time_id import AirbagParticleDecompositionTimeId
from .airbag_particle_id import AirbagParticleId
from .airbag_particle_inflation import AirbagParticleInflation
from .airbag_particle_inflation_id import AirbagParticleInflationId
from .airbag_particle_inflation_segment import AirbagParticleInflationSegment
from .airbag_particle_inflation_segment_id import AirbagParticleInflationSegmentId
from .airbag_particle_inflation_segment_time import AirbagParticleInflationSegmentTime
from .airbag_particle_inflation_segment_time_id import AirbagParticleInflationSegmentTimeId
from .airbag_particle_inflation_time import AirbagParticleInflationTime
from .airbag_particle_inflation_time_id import AirbagParticleInflationTimeId
from .airbag_particle_jet import AirbagParticleJet
from .airbag_particle_jet_id import AirbagParticleJetId
from .airbag_particle_jet_segment import AirbagParticleJetSegment
from .airbag_particle_jet_segment_id import AirbagParticleJetSegmentId
from .airbag_particle_jet_segment_time import AirbagParticleJetSegmentTime
from .airbag_particle_jet_segment_time_id import AirbagParticleJetSegmentTimeId
from .airbag_particle_jet_time import AirbagParticleJetTime
from .airbag_particle_jet_time_id import AirbagParticleJetTimeId
from .airbag_particle_molefraction import AirbagParticleMolefraction
from .airbag_particle_molefraction_id import AirbagParticleMolefractionId
from .airbag_particle_molefraction_segment import AirbagParticleMolefractionSegment
from .airbag_particle_molefraction_segment_id import AirbagParticleMolefractionSegmentId
from .airbag_particle_molefraction_segment_time import AirbagParticleMolefractionSegmentTime
from .airbag_particle_molefraction_segment_time_id import AirbagParticleMolefractionSegmentTimeId
from .airbag_particle_molefraction_time import AirbagParticleMolefractionTime
from .airbag_particle_molefraction_time_id import AirbagParticleMolefractionTimeId
from .airbag_particle_mpp import AirbagParticleMpp
from .airbag_particle_mpp_decomposition import AirbagParticleMppDecomposition
from .airbag_particle_mpp_decomposition_id import AirbagParticleMppDecompositionId
from .airbag_particle_mpp_decomposition_inflation import AirbagParticleMppDecompositionInflation
from .airbag_particle_mpp_decomposition_inflation_id import AirbagParticleMppDecompositionInflationId
from .airbag_particle_mpp_decomposition_inflation_segment import AirbagParticleMppDecompositionInflationSegment
from .airbag_particle_mpp_decomposition_inflation_segment_id import AirbagParticleMppDecompositionInflationSegmentId
from .airbag_particle_mpp_decomposition_inflation_segment_time import AirbagParticleMppDecompositionInflationSegmentTime
from .airbag_particle_mpp_decomposition_inflation_segment_time_id import AirbagParticleMppDecompositionInflationSegmentTimeId
from .airbag_particle_mpp_decomposition_inflation_time import AirbagParticleMppDecompositionInflationTime
from .airbag_particle_mpp_decomposition_inflation_time_id import AirbagParticleMppDecompositionInflationTimeId
from .airbag_particle_mpp_decomposition_jet import AirbagParticleMppDecompositionJet
from .airbag_particle_mpp_decomposition_jet_id import AirbagParticleMppDecompositionJetId
from .airbag_particle_mpp_decomposition_jet_segment import AirbagParticleMppDecompositionJetSegment
from .airbag_particle_mpp_decomposition_jet_segment_id import AirbagParticleMppDecompositionJetSegmentId
from .airbag_particle_mpp_decomposition_jet_segment_time import AirbagParticleMppDecompositionJetSegmentTime
from .airbag_particle_mpp_decomposition_jet_segment_time_id import AirbagParticleMppDecompositionJetSegmentTimeId
from .airbag_particle_mpp_decomposition_jet_time import AirbagParticleMppDecompositionJetTime
from .airbag_particle_mpp_decomposition_jet_time_id import AirbagParticleMppDecompositionJetTimeId
from .airbag_particle_mpp_decomposition_molefraction import AirbagParticleMppDecompositionMolefraction
from .airbag_particle_mpp_decomposition_molefraction_id import AirbagParticleMppDecompositionMolefractionId
from .airbag_particle_mpp_decomposition_molefraction_segment import AirbagParticleMppDecompositionMolefractionSegment
from .airbag_particle_mpp_decomposition_molefraction_segment_id import AirbagParticleMppDecompositionMolefractionSegmentId
from .airbag_particle_mpp_decomposition_molefraction_segment_time import AirbagParticleMppDecompositionMolefractionSegmentTime
from .airbag_particle_mpp_decomposition_molefraction_segment_time_id import AirbagParticleMppDecompositionMolefractionSegmentTimeId
from .airbag_particle_mpp_decomposition_molefraction_time import AirbagParticleMppDecompositionMolefractionTime
from .airbag_particle_mpp_decomposition_molefraction_time_id import AirbagParticleMppDecompositionMolefractionTimeId
from .airbag_particle_mpp_decomposition_segment import AirbagParticleMppDecompositionSegment
from .airbag_particle_mpp_decomposition_segment_id import AirbagParticleMppDecompositionSegmentId
from .airbag_particle_mpp_decomposition_segment_time import AirbagParticleMppDecompositionSegmentTime
from .airbag_particle_mpp_decomposition_segment_time_id import AirbagParticleMppDecompositionSegmentTimeId
from .airbag_particle_mpp_decomposition_time import AirbagParticleMppDecompositionTime
from .airbag_particle_mpp_decomposition_time_id import AirbagParticleMppDecompositionTimeId
from .airbag_particle_mpp_id import AirbagParticleMppId
from .airbag_particle_mpp_inflation import AirbagParticleMppInflation
from .airbag_particle_mpp_inflation_id import AirbagParticleMppInflationId
from .airbag_particle_mpp_inflation_segment import AirbagParticleMppInflationSegment
from .airbag_particle_mpp_inflation_segment_id import AirbagParticleMppInflationSegmentId
from .airbag_particle_mpp_inflation_segment_time import AirbagParticleMppInflationSegmentTime
from .airbag_particle_mpp_inflation_segment_time_id import AirbagParticleMppInflationSegmentTimeId
from .airbag_particle_mpp_inflation_time import AirbagParticleMppInflationTime
from .airbag_particle_mpp_inflation_time_id import AirbagParticleMppInflationTimeId
from .airbag_particle_mpp_jet import AirbagParticleMppJet
from .airbag_particle_mpp_jet_id import AirbagParticleMppJetId
from .airbag_particle_mpp_jet_segment import AirbagParticleMppJetSegment
from .airbag_particle_mpp_jet_segment_id import AirbagParticleMppJetSegmentId
from .airbag_particle_mpp_jet_segment_time import AirbagParticleMppJetSegmentTime
from .airbag_particle_mpp_jet_segment_time_id import AirbagParticleMppJetSegmentTimeId
from .airbag_particle_mpp_jet_time import AirbagParticleMppJetTime
from .airbag_particle_mpp_jet_time_id import AirbagParticleMppJetTimeId
from .airbag_particle_mpp_molefraction import AirbagParticleMppMolefraction
from .airbag_particle_mpp_molefraction_id import AirbagParticleMppMolefractionId
from .airbag_particle_mpp_molefraction_segment import AirbagParticleMppMolefractionSegment
from .airbag_particle_mpp_molefraction_segment_id import AirbagParticleMppMolefractionSegmentId
from .airbag_particle_mpp_molefraction_segment_time import AirbagParticleMppMolefractionSegmentTime
from .airbag_particle_mpp_molefraction_segment_time_id import AirbagParticleMppMolefractionSegmentTimeId
from .airbag_particle_mpp_molefraction_time import AirbagParticleMppMolefractionTime
from .airbag_particle_mpp_molefraction_time_id import AirbagParticleMppMolefractionTimeId
from .airbag_particle_mpp_segment import AirbagParticleMppSegment
from .airbag_particle_mpp_segment_id import AirbagParticleMppSegmentId
from .airbag_particle_mpp_segment_time import AirbagParticleMppSegmentTime
from .airbag_particle_mpp_segment_time_id import AirbagParticleMppSegmentTimeId
from .airbag_particle_mpp_time import AirbagParticleMppTime
from .airbag_particle_mpp_time_id import AirbagParticleMppTimeId
from .airbag_particle_segment import AirbagParticleSegment
from .airbag_particle_segment_id import AirbagParticleSegmentId
from .airbag_particle_segment_time import AirbagParticleSegmentTime
from .airbag_particle_segment_time_id import AirbagParticleSegmentTimeId
from .airbag_particle_time import AirbagParticleTime
from .airbag_particle_time_id import AirbagParticleTimeId
from .airbag_reference_geometry import AirbagReferenceGeometry
from .airbag_reference_geometry_birth import AirbagReferenceGeometryBirth
from .airbag_reference_geometry_birth_id import AirbagReferenceGeometryBirthId
from .airbag_reference_geometry_birth_rdt import AirbagReferenceGeometryBirthRdt
from .airbag_reference_geometry_id import AirbagReferenceGeometryId
from .airbag_reference_geometry_rdt import AirbagReferenceGeometryRdt
from .airbag_reference_geometry_rdt_birth import AirbagReferenceGeometryRdtBirth
from .airbag_reference_geometry_rdt_birth_id import AirbagReferenceGeometryRdtBirthId
from .airbag_reference_geometry_rdt_id import AirbagReferenceGeometryRdtId
from .airbag_shell_reference_geometry import AirbagShellReferenceGeometry
from .airbag_shell_reference_geometry_id import AirbagShellReferenceGeometryId
from .airbag_shell_reference_geometry_rdt import AirbagShellReferenceGeometryRdt
from .airbag_shell_reference_geometry_rdt_id import AirbagShellReferenceGeometryRdtId
from .airbag_simple_airbag_model import AirbagSimpleAirbagModel
from .airbag_simple_airbag_model_id import AirbagSimpleAirbagModelId
from .airbag_simple_pressure_volume import AirbagSimplePressureVolume
from .airbag_simple_pressure_volume_id import AirbagSimplePressureVolumeId
from .airbag_wang_nefske import AirbagWangNefske
from .airbag_wang_nefske_id import AirbagWangNefskeId
from .airbag_wang_nefske_jetting import AirbagWangNefskeJetting
from .airbag_wang_nefske_jetting_cm import AirbagWangNefskeJettingCm
from .airbag_wang_nefske_jetting_cm_id import AirbagWangNefskeJettingCmId
from .airbag_wang_nefske_jetting_id import AirbagWangNefskeJettingId
from .airbag_wang_nefske_jetting_pop import AirbagWangNefskeJettingPop
from .airbag_wang_nefske_jetting_pop_cm import AirbagWangNefskeJettingPopCm
from .airbag_wang_nefske_jetting_pop_cm_id import AirbagWangNefskeJettingPopCmId
from .airbag_wang_nefske_jetting_pop_id import AirbagWangNefskeJettingPopId
from .airbag_wang_nefske_multiple_jetting import AirbagWangNefskeMultipleJetting
from .airbag_wang_nefske_multiple_jetting_cm import AirbagWangNefskeMultipleJettingCm
from .airbag_wang_nefske_multiple_jetting_cm_id import AirbagWangNefskeMultipleJettingCmId
from .airbag_wang_nefske_multiple_jetting_id import AirbagWangNefskeMultipleJettingId
from .airbag_wang_nefske_multiple_jetting_pop import AirbagWangNefskeMultipleJettingPop
from .airbag_wang_nefske_multiple_jetting_pop_cm import AirbagWangNefskeMultipleJettingPopCm
from .airbag_wang_nefske_multiple_jetting_pop_cm_id import AirbagWangNefskeMultipleJettingPopCmId
from .airbag_wang_nefske_multiple_jetting_pop_id import AirbagWangNefskeMultipleJettingPopId
from .airbag_wang_nefske_pop import AirbagWangNefskePop
from .airbag_wang_nefske_pop_id import AirbagWangNefskePopId
