# Copyright (C) 2023 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""Module for DEFINE_TABLE keyword."""

import typing

from ansys.dyna.core.keywords.keyword_classes.auto.define.define_table import DefineTable as _AutoDefineTable


class DefineTable(_AutoDefineTable):
    """Manual extension of the auto-generated `DefineTable`.

    This file exists so local, repo-specific extensions do not modify the
    auto-generated file. Keep additions minimal to avoid surprising
    behavior when the auto classes are regenerated by the codegen.
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # List of DefineCurve objects linked to this table during import
        self._linked_curves: typing.List[typing.Any] = []

    @property
    def linked_curves(self) -> typing.List[typing.Any]:
        """List of `DefineCurve` keywords linked to this table.

        Populated by the import handler during `Deck.loads()`. Returns a list
        of curves that immediately follow this table in the deck.
        """
        return self._linked_curves
