open keyword "C:\pydyna_main\pydyna\src\ansys\dyna\core\pre\examples\isph\rigidtest\rigidtest.k"
 Time to read keyword file =  0.555 seconds
Warning - SECTION 10 not found:
  Referenced in *PART ID = 1
Warning - MAT 11 not found:
  Referenced in *PART ID = 1
Warning - SECTION 2 not found:
  Referenced in *PART ID = 4
Warning - MAT 912 not found:
  Referenced in *PART ID = 4
Warning - SECTION 2 not found:
  Referenced in *PART ID = 5
Warning - MAT 912 not found:
  Referenced in *PART ID = 5
Warning - SECTION 1 not found:
  Referenced in *PART ID = 6
Warning - MAT 911 not found:
  Referenced in *PART ID = 6
Warning - SECTION 10 not found:
  Referenced in *PART_INERTIA ID = 7
Warning - MAT 10 not found:
  Referenced in *PART_INERTIA ID = 7
Warning - SECTION 10 not found:
  Referenced in *PART ID = 8
Warning - MAT 11 not found:
  Referenced in *PART ID = 8
 Time to process element data =  0.250 seconds
Finished reading model
