"""
DEM API
==========

Module to create DEM dyna input deck
"""

import logging

from .dynabase import *  # noqa : F403


class DynaDEM(DynaBase):
    """Contains methods to create keyword related to discrete element method."""

    def __init__(self):
        DynaBase.__init__(self)

    def set_des(self, ndamp=0.0, tdamp=0.0, frics=0.0, fricr=0.0, normk=0.01, sheark=0.2857):
        """Define global control parameters for discrete element spheres.

        Parameters
        ----------
        ndamp : float
            Normal damping coefficient.
        tdamp : float
            Tangential damping coefficient.
        frics : float
            Static coefficient of friction,EQ.0: 3 DOF,NE.0: 6 DOF.
        fricr : float
            Rolling friction coefficient.
        normk : float
             Scale factor of normal spring constant.
        sheark : float
             ratio between sheark/normk.

        Returns
        -------
        bool
            "True" when successful, "False" when failed
        """
        ret = self.stub.CreateControlDiscreteElement(
            ControlDiscreteElementRequest(
                ndamp=ndamp,
                tdamp=tdamp,
                frics=frics,
                fricr=fricr,
                normk=normk,
                sheark=sheark,
            )
        )
        logging.info("Control DES Created...")
        return ret

    def create_define_de_mesh_surface(self, sid, type, despid, desxid, nquad=1, nsid=0, rsf=1.0):
        """Generate and place discrete element sphere (DES) elements on the surface of shell elements.

        Parameters
        ----------
        sid : int
            Part or part set ID for the region of the mesh upon which the DES elements will be placed.
        type : int
            SID type:type=0: Part set ID
                     type=1: Part ID
        despid : int
            Part ID for generated DES elements.
        desxid : int
            Section ID for generated DES elements.
        nquad : int
            Number of equally spaced DES elements created on a shell element in each local shell direction.
        nsid : int
            If defined, this card creates a node set with ID NSID for the nodes generated by this card.
        rsf : float
            Scale factor for determining the DES radius.

        Returns
        -------
        bool
            "True" when successful, "False" when failed
        """
        ret = self.stub.CreateDefineDEMeshSurface(
            DefineDEMeshSurfaceRequest(
                sid=sid,
                type=type,
                despid=despid,
                desxid=desxid,
                nquad=nquad,
                nsid=nsid,
                rsf=rsf,
            )
        )
        logging.info("Define discrete element mesh surface Created...")
        return ret

    def save_file(self):
        """Save keyword files.

        Returns
        -------
        bool
            "True" when successful, "False" when failed
        """
        self.set_accuracy(
            objective_stress_updates=Switch.ON,
            invariant_node_number=InvariantNode.ON_FOR_SHELL_TSHELL_SOLID,
            implicit_accuracy_flag=Switch.ON,
        )
        self.set_bulk_viscosity(bulk_viscosity_type=BulkViscosity.COMPUTE_INTERNAL_ENERGY_DISSIPATED)
        self.set_energy(
            hourglass_energy=EnergyFlag.COMPUTED,
            sliding_interface_energy=EnergyFlag.COMPUTED,
        )
        self.set_hourglass(
            controltype=HourglassControl.FLANAGAN_BELYTSCHKO_INTEGRATION_SOLID,
            coefficient=0,
        )
        self.create_control_shell(
            wrpang=0,
            esort=1,
            irnxx=0,
            istupd=4,
            theory=0,
            bwc=1,
            miter=1,
            proj=1,
            irquad=0,
        )
        self.create_control_contact(rwpnal=1.0, ignore=1, igactc=0)
        for obj in Contact.contactlist:
            obj.create()
        for obj in Gravity.gravitylist:
            obj.create()
        for obj in BeamPart.partlist:
            obj.set_property()
        for obj in ShellPart.partlist:
            obj.set_property()
        for obj in SolidPart.partlist:
            obj.set_property()
        for obj in IGAPart.partlist:
            obj.set_property()
        for obj in DiscretePart.partlist:
            obj.set_property()
        for obj in RigidwallCylinder.rwlist:
            obj.create()
        Constraint.create(self.stub)