# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kwprocess_pb2 as kwprocess__pb2


class kwC2SStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.kwSetFileName = channel.unary_unary(
                '/kwgrpc.kwC2S/kwSetFileName',
                request_serializer=kwprocess__pb2.kwFileName.SerializeToString,
                response_deserializer=kwprocess__pb2.kwFileNameReply.FromString,
                )
        self.Upload = channel.stream_unary(
                '/kwgrpc.kwC2S/Upload',
                request_serializer=kwprocess__pb2.Chunk.SerializeToString,
                response_deserializer=kwprocess__pb2.kwFileReply.FromString,
                )
        self.CreateTimestep = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateTimestep',
                request_serializer=kwprocess__pb2.TimestepRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.TimestepReply.FromString,
                )
        self.CreateTermination = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateTermination',
                request_serializer=kwprocess__pb2.TerminationRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.TerminationReply.FromString,
                )
        self.CreateContact = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateContact',
                request_serializer=kwprocess__pb2.ContactRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.ContactReply.FromString,
                )
        self.CreateDBBinary = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateDBBinary',
                request_serializer=kwprocess__pb2.DBBinaryRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.DBBinaryReply.FromString,
                )
        self.CreateRigidWallGeom = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateRigidWallGeom',
                request_serializer=kwprocess__pb2.RigidWallGeomRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.RigidWallGeomReply.FromString,
                )
        self.CreateContactAutomatic = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateContactAutomatic',
                request_serializer=kwprocess__pb2.ContactAutomaticRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.ContactAutomaticReply.FromString,
                )
        self.CreateContactTied = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateContactTied',
                request_serializer=kwprocess__pb2.ContactTiedRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.ContactTiedReply.FromString,
                )
        self.CreateDefineCurve = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateDefineCurve',
                request_serializer=kwprocess__pb2.DefineCurveRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.DefineCurveReply.FromString,
                )
        self.CreatePartSet = channel.unary_unary(
                '/kwgrpc.kwC2S/CreatePartSet',
                request_serializer=kwprocess__pb2.PartSetRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.PartSetReply.FromString,
                )
        self.CreateSectionIGAShell = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateSectionIGAShell',
                request_serializer=kwprocess__pb2.SectionIGAShellRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.SectionIGAShellReply.FromString,
                )
        self.CreateSectionSolid = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateSectionSolid',
                request_serializer=kwprocess__pb2.SectionSolidRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.SectionSolidReply.FromString,
                )
        self.CreateHourglass = channel.unary_unary(
                '/kwgrpc.kwC2S/CreateHourglass',
                request_serializer=kwprocess__pb2.HourglassRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.HourglassReply.FromString,
                )
        self.SetPartProperty = channel.unary_unary(
                '/kwgrpc.kwC2S/SetPartProperty',
                request_serializer=kwprocess__pb2.PartPropertyRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.PartPropertyReply.FromString,
                )
        self.SaveFile = channel.unary_unary(
                '/kwgrpc.kwC2S/SaveFile',
                request_serializer=kwprocess__pb2.SaveFileRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.SaveFileReply.FromString,
                )
        self.LoadFile = channel.unary_unary(
                '/kwgrpc.kwC2S/LoadFile',
                request_serializer=kwprocess__pb2.LoadFileRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.LoadFileReply.FromString,
                )
        self.Download = channel.unary_stream(
                '/kwgrpc.kwC2S/Download',
                request_serializer=kwprocess__pb2.DownloadRequest.SerializeToString,
                response_deserializer=kwprocess__pb2.Chunk.FromString,
                )


class kwC2SServicer(object):
    """Missing associated documentation comment in .proto file."""

    def kwSetFileName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTimestep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTermination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDBBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRigidWallGeom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContactAutomatic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContactTied(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDefineCurve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePartSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSectionIGAShell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSectionSolid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHourglass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPartProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_kwC2SServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'kwSetFileName': grpc.unary_unary_rpc_method_handler(
                    servicer.kwSetFileName,
                    request_deserializer=kwprocess__pb2.kwFileName.FromString,
                    response_serializer=kwprocess__pb2.kwFileNameReply.SerializeToString,
            ),
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=kwprocess__pb2.Chunk.FromString,
                    response_serializer=kwprocess__pb2.kwFileReply.SerializeToString,
            ),
            'CreateTimestep': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTimestep,
                    request_deserializer=kwprocess__pb2.TimestepRequest.FromString,
                    response_serializer=kwprocess__pb2.TimestepReply.SerializeToString,
            ),
            'CreateTermination': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTermination,
                    request_deserializer=kwprocess__pb2.TerminationRequest.FromString,
                    response_serializer=kwprocess__pb2.TerminationReply.SerializeToString,
            ),
            'CreateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContact,
                    request_deserializer=kwprocess__pb2.ContactRequest.FromString,
                    response_serializer=kwprocess__pb2.ContactReply.SerializeToString,
            ),
            'CreateDBBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDBBinary,
                    request_deserializer=kwprocess__pb2.DBBinaryRequest.FromString,
                    response_serializer=kwprocess__pb2.DBBinaryReply.SerializeToString,
            ),
            'CreateRigidWallGeom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRigidWallGeom,
                    request_deserializer=kwprocess__pb2.RigidWallGeomRequest.FromString,
                    response_serializer=kwprocess__pb2.RigidWallGeomReply.SerializeToString,
            ),
            'CreateContactAutomatic': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContactAutomatic,
                    request_deserializer=kwprocess__pb2.ContactAutomaticRequest.FromString,
                    response_serializer=kwprocess__pb2.ContactAutomaticReply.SerializeToString,
            ),
            'CreateContactTied': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContactTied,
                    request_deserializer=kwprocess__pb2.ContactTiedRequest.FromString,
                    response_serializer=kwprocess__pb2.ContactTiedReply.SerializeToString,
            ),
            'CreateDefineCurve': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDefineCurve,
                    request_deserializer=kwprocess__pb2.DefineCurveRequest.FromString,
                    response_serializer=kwprocess__pb2.DefineCurveReply.SerializeToString,
            ),
            'CreatePartSet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePartSet,
                    request_deserializer=kwprocess__pb2.PartSetRequest.FromString,
                    response_serializer=kwprocess__pb2.PartSetReply.SerializeToString,
            ),
            'CreateSectionIGAShell': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSectionIGAShell,
                    request_deserializer=kwprocess__pb2.SectionIGAShellRequest.FromString,
                    response_serializer=kwprocess__pb2.SectionIGAShellReply.SerializeToString,
            ),
            'CreateSectionSolid': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSectionSolid,
                    request_deserializer=kwprocess__pb2.SectionSolidRequest.FromString,
                    response_serializer=kwprocess__pb2.SectionSolidReply.SerializeToString,
            ),
            'CreateHourglass': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHourglass,
                    request_deserializer=kwprocess__pb2.HourglassRequest.FromString,
                    response_serializer=kwprocess__pb2.HourglassReply.SerializeToString,
            ),
            'SetPartProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPartProperty,
                    request_deserializer=kwprocess__pb2.PartPropertyRequest.FromString,
                    response_serializer=kwprocess__pb2.PartPropertyReply.SerializeToString,
            ),
            'SaveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFile,
                    request_deserializer=kwprocess__pb2.SaveFileRequest.FromString,
                    response_serializer=kwprocess__pb2.SaveFileReply.SerializeToString,
            ),
            'LoadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadFile,
                    request_deserializer=kwprocess__pb2.LoadFileRequest.FromString,
                    response_serializer=kwprocess__pb2.LoadFileReply.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=kwprocess__pb2.DownloadRequest.FromString,
                    response_serializer=kwprocess__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kwgrpc.kwC2S', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class kwC2S(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def kwSetFileName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/kwSetFileName',
            kwprocess__pb2.kwFileName.SerializeToString,
            kwprocess__pb2.kwFileNameReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/kwgrpc.kwC2S/Upload',
            kwprocess__pb2.Chunk.SerializeToString,
            kwprocess__pb2.kwFileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTimestep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateTimestep',
            kwprocess__pb2.TimestepRequest.SerializeToString,
            kwprocess__pb2.TimestepReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTermination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateTermination',
            kwprocess__pb2.TerminationRequest.SerializeToString,
            kwprocess__pb2.TerminationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateContact',
            kwprocess__pb2.ContactRequest.SerializeToString,
            kwprocess__pb2.ContactReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDBBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateDBBinary',
            kwprocess__pb2.DBBinaryRequest.SerializeToString,
            kwprocess__pb2.DBBinaryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRigidWallGeom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateRigidWallGeom',
            kwprocess__pb2.RigidWallGeomRequest.SerializeToString,
            kwprocess__pb2.RigidWallGeomReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateContactAutomatic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateContactAutomatic',
            kwprocess__pb2.ContactAutomaticRequest.SerializeToString,
            kwprocess__pb2.ContactAutomaticReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateContactTied(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateContactTied',
            kwprocess__pb2.ContactTiedRequest.SerializeToString,
            kwprocess__pb2.ContactTiedReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDefineCurve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateDefineCurve',
            kwprocess__pb2.DefineCurveRequest.SerializeToString,
            kwprocess__pb2.DefineCurveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePartSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreatePartSet',
            kwprocess__pb2.PartSetRequest.SerializeToString,
            kwprocess__pb2.PartSetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSectionIGAShell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateSectionIGAShell',
            kwprocess__pb2.SectionIGAShellRequest.SerializeToString,
            kwprocess__pb2.SectionIGAShellReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSectionSolid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateSectionSolid',
            kwprocess__pb2.SectionSolidRequest.SerializeToString,
            kwprocess__pb2.SectionSolidReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateHourglass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/CreateHourglass',
            kwprocess__pb2.HourglassRequest.SerializeToString,
            kwprocess__pb2.HourglassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPartProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/SetPartProperty',
            kwprocess__pb2.PartPropertyRequest.SerializeToString,
            kwprocess__pb2.PartPropertyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/SaveFile',
            kwprocess__pb2.SaveFileRequest.SerializeToString,
            kwprocess__pb2.SaveFileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kwgrpc.kwC2S/LoadFile',
            kwprocess__pb2.LoadFileRequest.SerializeToString,
            kwprocess__pb2.LoadFileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/kwgrpc.kwC2S/Download',
            kwprocess__pb2.DownloadRequest.SerializeToString,
            kwprocess__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
