#!/bin/sh
#
# Do some basic ssh setup
#
rm -rf ssh
mkdir ssh
ssh-keygen -q -b 2048 -f ssh/id_rsa -N ""
echo "Host *" > ssh/config
echo "  StrictHostKeyChecking no" >> ssh/config
#
chmod -R 755 *
#
# Build container
#
docker build -t dyna_solver_v04 . 
