version: "3.3"
name: "dyna"
services:
  dyna:
    build: ./
    networks:
      - dyna_internal
    volumes:
       - /rundir
    cap_add:
      - SYS_PTRACE
    ports:
      - target: 5000
        published: 5000
        mode: ingress
    user: mpirun
    environment:
      - LSTC_LICENSE_SERVER=lvrpanda.ansys.com
    entrypoint: ["/ansys_inc/server.py","dyna"]
networks:
  dyna_internal: