$# LS-DYNA Keyword file created by LS-PrePost(R) V4.10 (Beta)-02Aug2022
$# Created on Aug-10-2022 (15:33:05)
*KEYWORD
*TITLE
$#                                                                         title
2012 TOYOTA CAMRY Roof Crush (NCAC)
*INCLUDE
501_RIG_BAR_roof_crush_platen5.key
*INCLUDE
Camry_V1_NoSusAndPowerTrain_impl7.k
*INCLUDE
Camry_V1_NoSusAndPowerTrain_impl7_nodes.k
*INCLUDE
xtra_sw.k
*INCLUDE
weld7.k
*INCLUDE
roof_welds.k
*END
