open keyword "D:\pyDynavenv\pyDyna\src\ansys\dyna\core\pre\examples\icfd\cylinder_flow\cylinder_flow.k"
 Time to read keyword file =  0.141 seconds
 Time to process element data =  0.109 seconds
Finished reading model
open keyword "D:\!WORK\ICFD\ICFDPRE_EXAMPLE\Basics\7_User_defined_mesh\i.k"
LS-PrePost encounters an error when open D:\pyDynavenv\pyDyna\src\ansys\dyna\core\pre\examples\icfd\cylinder_flow\mesh.k
because the path is not found
Error - Include File mesh.k Not open
  Error occurs in file D:\!WORK\ICFD\ICFDPRE_EXAMPLE\Basics\7_User_defined_mesh\i.k line # 31
Save Config. parameters to file C:\Users\dell\AppData\Roaming\LSTC\LS-PrePost4.10\lsppconf
