# Copyright (C) 2021 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Auto-generated imports for control domain

from .control_2d_remeshing_region import Control2DRemeshingRegion
from .control_accuracy import ControlAccuracy
from .control_acoustic import ControlAcoustic
from .control_acoustic_coupling import ControlAcousticCoupling
from .control_acoustic_spectral import ControlAcousticSpectral
from .control_adapstep import ControlAdapstep
from .control_adapt import ControlAdapt
from .control_adaptive import ControlAdaptive
from .control_adaptive_curve import ControlAdaptiveCurve
from .control_airbag import ControlAirbag
from .control_ale import ControlAle
from .control_bulk_viscosity import ControlBulkViscosity
from .control_check import ControlCheck
from .control_check_shell import ControlCheckShell
from .control_coarsen import ControlCoarsen
from .control_constranined import ControlConstranined
from .control_contact import ControlContact
from .control_coupling import ControlCoupling
from .control_cpm import ControlCpm
from .control_cpu import ControlCpu
from .control_cr_mpp_decomposition_deformed_geometry import ControlCrMppDecompositionDeformedGeometry
from .control_cr_mpp_decomposition_flag_stress_strain_curve import ControlCrMppDecompositionFlagStressStrainCurve
from .control_cr_mpp_material_model_driver import ControlCrMppMaterialModelDriver
from .control_damping import ControlDamping
from .control_debug import ControlDebug
from .control_discrete_element import ControlDiscreteElement
from .control_dynamic_relaxation import ControlDynamicRelaxation
from .control_efg import ControlEfg
from .control_energy import ControlEnergy
from .control_eos_user_library import ControlEosUserLibrary
from .control_explicit_thermal_ale_coupling import ControlExplicitThermalAleCoupling
from .control_explicit_thermal_boundary import ControlExplicitThermalBoundary
from .control_explicit_thermal_contact import ControlExplicitThermalContact
from .control_explicit_thermal_initial import ControlExplicitThermalInitial
from .control_explicit_thermal_output import ControlExplicitThermalOutput
from .control_explicit_thermal_properties import ControlExplicitThermalProperties
from .control_explicit_thermal_solver import ControlExplicitThermalSolver
from .control_explosive_shadow import ControlExplosiveShadow
from .control_forming_autocheck import ControlFormingAutocheck
from .control_forming_autoposition_parameter import ControlFormingAutopositionParameter
from .control_forming_autoposition_parameter_positive import ControlFormingAutopositionParameterPositive
from .control_forming_autoposition_parameter_set import ControlFormingAutopositionParameterSet
from .control_forming_autoposition_parameter_set_positive import ControlFormingAutopositionParameterSetPositive
from .control_forming_auto_net import ControlFormingAutoNet
from .control_forming_bestfit import ControlFormingBestfit
from .control_forming_bestfit_vector import ControlFormingBestfitVector
from .control_forming_blankmesh import ControlFormingBlankmesh
from .control_forming_generate_blankmesh import ControlFormingGenerateBlankmesh
from .control_forming_home_gap import ControlFormingHomeGap
from .control_forming_initial_thickness import ControlFormingInitialThickness
from .control_forming_maxid import ControlFormingMaxid
from .control_forming_onestep import ControlFormingOnestep
from .control_forming_onestep_auto_constraint import ControlFormingOnestepAutoConstraint
from .control_forming_onestep_drawbead import ControlFormingOnestepDrawbead
from .control_forming_onestep_friction import ControlFormingOnestepFriction
from .control_forming_onestep_ortho import ControlFormingOnestepOrtho
from .control_forming_onestep_quad import ControlFormingOnestepQuad
from .control_forming_onestep_quad2 import ControlFormingOnestepQuad2
from .control_forming_onestep_tria import ControlFormingOnestepTria
from .control_forming_output import ControlFormingOutput
from .control_forming_output_intfor import ControlFormingOutputIntfor
from .control_forming_parameter_read import ControlFormingParameterRead
from .control_forming_position import ControlFormingPosition
from .control_forming_pre_bending import ControlFormingPreBending
from .control_forming_pre_bending_local import ControlFormingPreBendingLocal
from .control_forming_projection import ControlFormingProjection
from .control_forming_remove_adaptive_constraints import ControlFormingRemoveAdaptiveConstraints
from .control_forming_scrap_fall import ControlFormingScrapFall
from .control_forming_shell_to_tshell import ControlFormingShellToTshell
from .control_forming_stoning import ControlFormingStoning
from .control_forming_strain_ratio_smooth import ControlFormingStrainRatioSmooth
from .control_forming_template import ControlFormingTemplate
from .control_forming_tipping import ControlFormingTipping
from .control_forming_toleranc import ControlFormingToleranc
from .control_forming_travel import ControlFormingTravel
from .control_forming_trimming import ControlFormingTrimming
from .control_forming_trim_merge import ControlFormingTrimMerge
from .control_forming_trim_solid_refinement import ControlFormingTrimSolidRefinement
from .control_forming_unflanging import ControlFormingUnflanging
from .control_forming_unflanging_output import ControlFormingUnflangingOutput
from .control_forming_user import ControlFormingUser
from .control_frequency_domain import ControlFrequencyDomain
from .control_frequency_response_function import ControlFrequencyResponseFunction
from .control_hourglass import ControlHourglass
from .control_hourglass_936 import ControlHourglass936
from .control_implicit_auto import ControlImplicitAuto
from .control_implicit_auto_dyn import ControlImplicitAutoDyn
from .control_implicit_auto_spr import ControlImplicitAutoSpr
from .control_implicit_buckle import ControlImplicitBuckle
from .control_implicit_consistent_mass import ControlImplicitConsistentMass
from .control_implicit_dynamic import ControlImplicitDynamic
from .control_implicit_dynamics import ControlImplicitDynamics
from .control_implicit_dynamics_dyn import ControlImplicitDynamicsDyn
from .control_implicit_dynamics_spr import ControlImplicitDynamicsSpr
from .control_implicit_eigenvalue import ControlImplicitEigenvalue
from .control_implicit_eigenvalues import ControlImplicitEigenvalues
from .control_implicit_forming import ControlImplicitForming
from .control_implicit_forming_dyn import ControlImplicitFormingDyn
from .control_implicit_forming_spr import ControlImplicitFormingSpr
from .control_implicit_general import ControlImplicitGeneral
from .control_implicit_general_dyn import ControlImplicitGeneralDyn
from .control_implicit_general_spr import ControlImplicitGeneralSpr
from .control_implicit_inertia_relief import ControlImplicitInertiaRelief
from .control_implicit_joints import ControlImplicitJoints
from .control_implicit_linear import ControlImplicitLinear
from .control_implicit_modal_dynamic import ControlImplicitModalDynamic
from .control_implicit_modal_dynamic_damping import ControlImplicitModalDynamicDamping
from .control_implicit_modal_dynamic_damping_frequency_range import ControlImplicitModalDynamicDampingFrequencyRange
from .control_implicit_modal_dynamic_damping_specific import ControlImplicitModalDynamicDampingSpecific
from .control_implicit_modal_dynamic_mode_generate import ControlImplicitModalDynamicModeGenerate
from .control_implicit_modal_dynamic_mode_list import ControlImplicitModalDynamicModeList
from .control_implicit_modes import ControlImplicitModes
from .control_implicit_modes_binary import ControlImplicitModesBinary
from .control_implicit_nonlinear import ControlImplicitNonlinear
from .control_implicit_ordering import ControlImplicitOrdering
from .control_implicit_residual_vector import ControlImplicitResidualVector
from .control_implicit_rotational_dynamics import ControlImplicitRotationalDynamics
from .control_implicit_solution import ControlImplicitSolution
from .control_implicit_solution_dyn import ControlImplicitSolutionDyn
from .control_implicit_solution_spr import ControlImplicitSolutionSpr
from .control_implicit_solver import ControlImplicitSolver
from .control_implicit_solver_dyn import ControlImplicitSolverDyn
from .control_implicit_solver_spr import ControlImplicitSolverSpr
from .control_implicit_ssd_direct import ControlImplicitSsdDirect
from .control_implicit_stabilisation import ControlImplicitStabilisation
from .control_implicit_stabilization import ControlImplicitStabilization
from .control_implicit_stabilization_dyn import ControlImplicitStabilizationDyn
from .control_implicit_stabilization_spr import ControlImplicitStabilizationSpr
from .control_implicit_static_condensation import ControlImplicitStaticCondensation
from .control_implicit_static_condensation_binary import ControlImplicitStaticCondensationBinary
from .control_implicit_termination import ControlImplicitTermination
from .control_lsda import ControlLsda
from .control_mat import ControlMat
from .control_mpp_contact_groupable import ControlMppContactGroupable
from .control_mpp_decomposition_adaptive import ControlMppDecompositionAdaptive
from .control_mpp_decomposition_arrange_parts import ControlMppDecompositionArrangeParts
from .control_mpp_decomposition_automatic import ControlMppDecompositionAutomatic
from .control_mpp_decomposition_bagref import ControlMppDecompositionBagref
from .control_mpp_decomposition_check_speed import ControlMppDecompositionCheckSpeed
from .control_mpp_decomposition_contact_distribute import ControlMppDecompositionContactDistribute
from .control_mpp_decomposition_contact_isolate import ControlMppDecompositionContactIsolate
from .control_mpp_decomposition_disable_unref_curves import ControlMppDecompositionDisableUnrefCurves
from .control_mpp_decomposition_distribute_ale_element import ControlMppDecompositionDistributeAleElement
from .control_mpp_decomposition_distribute_ale_elements import ControlMppDecompositionDistributeAleElements
from .control_mpp_decomposition_distribute_sph_element import ControlMppDecompositionDistributeSphElement
from .control_mpp_decomposition_distribute_sph_elements import ControlMppDecompositionDistributeSphElements
from .control_mpp_decomposition_elcost import ControlMppDecompositionElcost
from .control_mpp_decomposition_file import ControlMppDecompositionFile
from .control_mpp_decomposition_file_read import ControlMppDecompositionFileRead
from .control_mpp_decomposition_file_write import ControlMppDecompositionFileWrite
from .control_mpp_decomposition_method import ControlMppDecompositionMethod
from .control_mpp_decomposition_nodistribute_des_elements import ControlMppDecompositionNodistributeDesElements
from .control_mpp_decomposition_numproc import ControlMppDecompositionNumproc
from .control_mpp_decomposition_outdecomp import ControlMppDecompositionOutdecomp
from .control_mpp_decomposition_partset_distribute import ControlMppDecompositionPartsetDistribute
from .control_mpp_decomposition_parts_distribute import ControlMppDecompositionPartsDistribute
from .control_mpp_decomposition_rcblog import ControlMppDecompositionRcblog
from .control_mpp_decomposition_redecomposition import ControlMppDecompositionRedecomposition
from .control_mpp_decomposition_redecomposition_once import ControlMppDecompositionRedecompositionOnce
from .control_mpp_decomposition_scale_contact_cost import ControlMppDecompositionScaleContactCost
from .control_mpp_decomposition_scale_factor_sph import ControlMppDecompositionScaleFactorSph
from .control_mpp_decomposition_show import ControlMppDecompositionShow
from .control_mpp_decomposition_transformation import ControlMppDecompositionTransformation
from .control_mpp_io_binoutonly import ControlMppIoBinoutonly
from .control_mpp_io_lstc_reduce import ControlMppIoLstcReduce
from .control_mpp_io_nobeamout import ControlMppIoNobeamout
from .control_mpp_io_nod3dump import ControlMppIoNod3Dump
from .control_mpp_io_nodump import ControlMppIoNodump
from .control_mpp_io_nofull import ControlMppIoNofull
from .control_mpp_io_swapbytes import ControlMppIoSwapbytes
from .control_mpp_pfile import ControlMppPfile
from .control_mpp_rebalance import ControlMppRebalance
from .control_nonlocal import ControlNonlocal
from .control_output import ControlOutput
from .control_parallel import ControlParallel
from .control_pore_air import ControlPoreAir
from .control_pore_fluid import ControlPoreFluid
from .control_pzelectric import ControlPzelectric
from .control_reference_configuration import ControlReferenceConfiguration
from .control_reference_configuraion_iter import ControlReferenceConfiguraionIter
from .control_reference_control_volume_coordinates import ControlReferenceControlVolumeCoordinates
from .control_refine_ale import ControlRefineAle
from .control_refine_ale2d import ControlRefineAle2D
from .control_refine_mpp_distribution import ControlRefineMppDistribution
from .control_refine_shell import ControlRefineShell
from .control_refine_solid import ControlRefineSolid
from .control_remeshing import ControlRemeshing
from .control_remeshing_efg import ControlRemeshingEfg
from .control_require_revision import ControlRequireRevision
from .control_rigid import ControlRigid
from .control_segments_in_ale_coupling import ControlSegmentsInAleCoupling
from .control_shell import ControlShell
from .control_solid import ControlSolid
from .control_solution import ControlSolution
from .control_sph import ControlSph
from .control_sph_incompressible import ControlSphIncompressible
from .control_spotweld_beam import ControlSpotweldBeam
from .control_staged_construction import ControlStagedConstruction
from .control_start import ControlStart
from .control_steady_state_rolling import ControlSteadyStateRolling
from .control_structured import ControlStructured
from .control_structured_term import ControlStructuredTerm
from .control_subcycle import ControlSubcycle
from .control_subcycle_mass_scaled_part import ControlSubcycleMassScaledPart
from .control_subcycle_mass_scaled_part_set import ControlSubcycleMassScaledPartSet
from .control_termination import ControlTermination
from .control_thermal_eigenvalue import ControlThermalEigenvalue
from .control_thermal_forming import ControlThermalForming
from .control_thermal_nonlinear import ControlThermalNonlinear
from .control_thermal_solver import ControlThermalSolver
from .control_thermal_timestep import ControlThermalTimestep
from .control_timestep import ControlTimestep
from .control_timestep import ControlTimeStep
from .control_units import ControlUnits
from .control_vibro_acoustic import ControlVibroAcoustic
