"""
DEM API
==========

Module to create DEM dyna input deck
"""

import logging

from .dynabase import *  # noqa : F403


class DynaDEM(DynaBase):
    """Contains methods to create keyword related to discrete element method."""

    def __init__(self):
        DynaBase.__init__(self)

    def set_des(self, ndamp=0.0, tdamp=0.0, frics=0.0, fricr=0.0, normk=0.01, sheark=0.2857):
        """Define global control parameters for discrete element spheres.

        Parameters
        ----------
        ndamp : float
            Normal damping coefficient.
        tdamp : float
            Tangential damping coefficient.
        frics : float
            Static coefficient of friction,EQ.0: 3 DOF,NE.0: 6 DOF.
        fricr : float
            Rolling friction coefficient.
        normk : float
             Scale factor of normal spring constant.
        sheark : float
             ratio between sheark/normk.

        Returns
        -------
        bool
            "True" when successful, "False" when failed
        """
        ret = self.stub.CreateControlDiscreteElement(
            ControlDiscreteElementRequest(
                ndamp=ndamp,
                tdamp=tdamp,
                frics=frics,
                fricr=fricr,
                normk=normk,
                sheark=sheark,
            )
        )
        logging.info("Control DES Created...")
        return ret

    def create_define_de_mesh_surface(self, sid, type, despid, desxid, nquad=1, nsid=0, rsf=1.0):
        """Generate and place discrete element sphere (DES) elements on the surface of shell elements.

        Parameters
        ----------
        sid : int
            Part or part set ID for the region of the mesh upon which the DES elements will be placed.
        type : int
            SID type:type=0: Part set ID
                     type=1: Part ID
        despid : int
            Part ID for generated DES elements.
        desxid : int
            Section ID for generated DES elements.
        nquad : int
            Number of equally spaced DES elements created on a shell element in each local shell direction.
        nsid : int
            If defined, this card creates a node set with ID NSID for the nodes generated by this card.
        rsf : float
            Scale factor for determining the DES radius.

        Returns
        -------
        bool
            "True" when successful, "False" when failed
        """
        ret = self.stub.CreateDefineDEMeshSurface(
            DefineDEMeshSurfaceRequest(
                sid=sid,
                type=type,
                despid=despid,
                desxid=desxid,
                nquad=nquad,
                nsid=nsid,
                rsf=rsf,
            )
        )
        logging.info("Define discrete element mesh surface Created...")
        return ret

    def save_file(self):
        """Save keyword files.

        Returns
        -------
        bool
            "True" when successful, "False" when failed
        """
        DynaBase.save_file(self)


class DEMAnalysis:
    """Activate DEM analysis and define associated control parameters."""

    def __init__(self):
        self.defined_des = False
        self.stub = DynaBase.get_stub()

    def set_des(
        self,
        normal_damping_coeff=0.0,
        tangential_damping_coeff=0.0,
        static_friction_coeff=0.0,
        rolling_friction_coeff=0.0,
        normal_spring_constant_sf=0.01,
        ratio=0.2857,
    ):
        """Define global control parameters for discrete element spheres.

        Parameters
        ----------
        analysis_type : ICFD_AnalysisType
            Analysis type.
        """
        self.defined_des = True
        self.ndamp = normal_damping_coeff
        self.tdamp = tangential_damping_coeff
        self.frics = static_friction_coeff
        self.fricr = rolling_friction_coeff
        self.normk = normal_spring_constant_sf
        self.sheark = ratio

    def create(self):
        """Create DEM analysis."""
        if self.defined_des:
            self.stub.CreateControlDiscreteElement(
                ControlDiscreteElementRequest(
                    ndamp=self.ndamp,
                    tdamp=self.tdamp,
                    frics=self.frics,
                    fricr=self.fricr,
                    normk=self.normk,
                    sheark=self.sheark,
                )
            )
